### ISSUE TITLE
fork: images get dropped instead of made dummies

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1620]
This needs a "wrong" context definition in the context.yml: It should leave out su ceramic photos from the contexts:
```
config:
  format_version: 3
  contexts:
      cm_images:
        type: file_search
        scope:
          collected_material:
            collected_material_photo: {}
#            su_ceramics:
#              pottery_images: {}
#      su_ceramics_images:
#        type: file_search
#        scope:
#          su_ceramics:
#            pottery_images: {}
```
That way there are images in su-ceramics that are not connected to any context or identifier. And this is what triggers the issue:

- they have not at all been transported to the new workstation, not as dummies. I don't have an explanation.
- after I configured the su ceramic images in kiosk properly they were transported. But I need to understand why they were not transported at all before. That does not seem right. Candids are not dropped from the images table but marked as dummies. No image record should get dropped.

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/1617#issuecomment-1114738362_
