### ISSUE TITLE
File Import: command line tool

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1976]
To securely start the file import on Beset until we have #639 and as a generally helpful tool I shall make a command line tool to do file imports. So something that runs in the console and does not run into timeouts.

Since the file import gets pretty complex control information, what about using a json for it that contains exactly what the fileimportcontroller would receive from the Kiosk UI? In that case I could just create a template by starting some phantom import with all settings ready and fish the json out from the logs or from a file. Something like that.

**Comment by urapadmin** [comment]
I used a yaml file. Looks like this when using just the qr code filter:
```yaml
file_import:
  recursive: True
  add_needs_context: False
#  file_extensions: "jpg,nef"
#  tags: "import_091256"
file_import_filters:
  fileimportqrcodefilter:
    get_identifier: True
    get_date: True
    recognition_strategy: "qr_code_peru"

```
