### ISSUE TITLE
Q&V: Decimal not JSON serializable

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2022]
if a KioskQuery of type SQL returns a decimal, e.g. because there is a count or sum function used in sql, it can't be returned by the kiosk server because for some reason it is a Decimal type and that one cannot be serialized to JSON, indeed. 
A workaround is to cast the decimal to float in the sql statement, but that's really a hack. Something like that should just work out of the box.

Here is the kiosk query definition with the cast:

```YAML
header:
  version: 1
meta:
  query_type: StructuredKioskQuery
variables:
  unit_id: ["dsd('unit', 'arch_context')"]
queries:
  'material_types_of_unit_x_sql':
    name: 'What materials (and how much of each) were found in unit x?'
    description: 'Lists the materials found in a certain unit and shows count and weight by material'
    type: 'SQL'
    output_type: 'list'
    query: "
      select unit.arch_context unit_id,
       cm.type material,
       sum(cm.weight)::float weight,
       sum(cm.quantity)::float quantity
       from {{unit}} unit
         inner join {{locus}} locus on unit.uid = locus.uid_unit
         inner join {{collected_material}} cm on locus.uid = cm.uid_locus
      where unit.arch_context = {{#unit_id}}
      group by unit.arch_context, cm.type
      order by sum(cm.weight) desc,sum(cm.quantity) desc, cm.type"
    column_information:
      unit_id: DSD('unit','arch_context')
      material: DSD('collected_material','type')
      weight: DSD('collected_material','weight')
      quantity: DSD('collected_material','quantity')

```
