### ISSUE TITLE
file import: all the file import types show the whole set of available qr code strategies

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2287]
But they should not.  They should only show the ones that are allowed for them:

``` YAML
    filesequence_import:
      FileImportQRCodeFilter:
        active: True
        get_excavation_context: True
        get_date: True
        priority: 30
        recognition_strategy: qr_code_sequences
        image_manipulation_sets:
          - qr_code_black_velvet
          - qr_code_sequences

```

Also: The default selection should either be what the user last selected or what is set as "recognition_strategy" in the config of the specific module's FileImportQRCodeFilter section.
