### ISSUE TITLE
View: Additions to the UIC format

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2305]
### "include_uic_literals"
I do suspect that UIC files are written either to set general styles that apply everywhere OR they are written to serve a certain scenario.
In that case one would have to repeat the selector over and over again like here with "view_ui":

``` yaml
# view_ui && dsd('locus','type')
element_type:
  name: "selection"
  items:
    lookup_type: "table"
    topic: "locus_types"
    selection: ["type_name"]
    key: "id"

```
I propose to add a `include_uic_literals` attribute to the `# header` that simply applies a bunch of uic literals to all selectors so that one does not need to repeat them all the time

### multiple selectors
If several selectors lead to the same uic block it should be possible to stack them:
``` yaml
# dsd('unit','excavator_full_name') && view-ui
# dsd('unit','name') && view-ui
element_type:
  visible: "value"
```
