### ISSUE TITLE
Query & View: view-ui literal does not seem to be applied correctly

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2307]
the selector 
``` YAML
#dsd('locus','type') && view-ui && view_type:list
element_type:
  text: "#(unit/term_for_locus) type"

```
did not work, apparently because the view-ui literal is not active when getting the view from the api. After I removed it from the selector everything worked.
