### ISSUE TITLE
Q&V: Add the latest changes made in View to the Query part

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2313]
- Labels are not shown correctly anymore
- one query does not even work anymore
see also 
- [x] #2304 and 
- [x] #2270

**Comment by urapadmin** [comment]
see also #2304 and #2270

**Comment by urapadmin** [comment]
okay, the query was a CQL query selecting an additional field like this:

```YAML
          locus_identifier:
            field_or_instruction: locus.identifier()
            default: ""
```

The issue here is that the locus table has more than one field marked as identifier(), although one of them is in fact marked as identifier("additional") but that does not seem to matter:
```YAML
locus:
  structure:
    1:
      arch_context: [datatype(VARCHAR), identifier(), skip_index_on("hidden"), label("locus")]
      alternate_id: [datatype(VARCHAR), identifier("additional"), skip_index_on("hidden")]

```
The result is an error message like this:
´´table {table} has more than one field with instruction {field}. That is not supported by KioskContext, right now.")``

If have solved it for now in the query by switching to ``locus.arch_context`` but will make this a ticket since it could be solved.
