### ISSUE TITLE
Q&V: UIC / PLD Priorities for elements are not working properly

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2315]
I have a locus_relations.list in my PLD like this:

```YAML
locus_relations.list:
  record_type: locus_relations
  view_type: list  # (can be list, sheet or file_list or harris_matrix)
  max_height: 20em
  fields_selection: dsd
  layout_settings:
     ...
  ui_elements:
    uid_sketch:
      layout:
        min_width: max
        min_height: max
      element_type:
        name: "File"
        file_description: bottom
        resolution: small
        fit_content: contain
```

The name: "File" attribute does not prevail. Instead the ui-element for the sketch becomes a name: "TextField" for the client. I suspect that is what the datatype dictates. But explicit PLD settings must always dominate what comes from UIC.
Once I add the name: "File" as a uic selector everything works:

```YAML
#dsd('locus_relations','uid_sketch') && view_type:list
element_type:
  name: "File"
```
