### ISSUE TITLE
Q&V: Auto-generate the lookup key_field

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2316]
Currently I have to define a lookup and state the key field:
```
    to_locus:
      element_type:
        text: "#(unit/term_for_locus)"
        name: "TextField"
        value: "#(locus_relations/uid_locus_2_related)"
        lookup:
          lookup_type: "record"
          record_type: "locus"
          display_value: "arch_context"
          key_field: "uid"

```
That's redundant because there is also the loopup relation in the DSD:
`uid_locus_2_related: [datatype(UUID), "lookup('locus', 'uid')"]`

I thought to get the key field into the lookup data from the DSD lookup statement on the client side. But first this would be insane and slow to always lookup and interpret the DSD and second I don't even know when resolving the lookup on the client side which lookup statement in the dsd was responsible. At least not on the client's side. Instead of stating the key_field manually in the PLD, I want to try to make the server auto-generate the key_field entry (if it isn't set manually) when it is creating the record for the lookup data.
