### ISSUE TITLE
Q&V: Allow # notation in the description fields of query definitions

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2323]
Something like this should work:
```YAML
queries:
  'sites and units':
    name: 'what #($/constants/name_for_site) and #($/constants/name_for_unit) exist?'
    description: 'Lists all the #($/constants/name_for_site) and their #($/constants/name_for_unit)'
```

As plurals will be needed, too, the # notation might even need to be refined for this. Unless I can find the plural somewhere in the dictionary.
