### ISSUE TITLE
Q&V: site identifier does not work anymore after changes to the DSD

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2325]
I am not sure if it even has anything to do with my dsd changes. The responsible ui element is currently defined as 
```
        ui_elements:
          id_site:
            element_type:
              is_identifier: true
              links_to: "site"

```
And when I click on it, I get``queryandviewapp.js:38893 Uncaught TypeError: Cannot read properties of undefined (reading 'element_type')``
