### ISSUE TITLE
Q&V: Including a site note photos independent of site notes does not work

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2378]
I tried to include site note photos simply in an independent sheet in the site view.
But it does not seem to work: no records are found. Might be that the 1 : N : M relation does not work.
This is what I tried:
```yaml
site_note_photos.list:
  record_type: site_note_photo
  view_type: list
  fields_selection: dsd
  layout_settings:
    type: list
    orchestration_strategy: gallery
    order: [ uid_image, modified, modified_by ]
  ui_elements:
    note:
      layout:
        min_width: 70%
    uid_image:
      element_type:
        name: "File"

```

I don't get any errors but simply no records.
