### ISSUE TITLE
Kiosk: Project-specific autoload_plugins configuration

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2468]
in the case of the autoload_plugins I will add a new configuration key "autoload_plugins_{projectid}" where {projectid} must be the id of the current project:

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2467#issuecomment-1892832881_

**Comment by urapadmin** [comment]
### Kiosk 1.5.20
this can be used now for sync_plugins: 
```
config:
  project_id: 'buap'
  autoload_plugins_buap:
    - 'buap_ancdb_bridge'

```
The items in the ''autoload_plugins_buap'' (with buap being the curent project's id) list are added to the contents of the normal ''autoload_plugins''
