### ISSUE TITLE
Q&V: apply_uic_literal does not work 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2708]
> - loci in the unit / locus list have no foot step to jump to the locus

The reason for this is that there is a UIC block that's being applied on View level although it should be limited to the topic query-ui:

```YAML
# header
version: 1
apply_uic_literal: "&& query-ui"

# dsd('locus','arch_context')
element_type:
  text: "#($/constants/labels/locus)"
  name: "selectionX"
  items:
    lookup_type: "table"
    topic: "locus"
    selection: ["arch_context"]
    key: "arch_context"


```
_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2691#issuecomment-2099080692_
