### ISSUE TITLE
UI Component: layout/max_height does not work

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2721]
This code should limit the purpose field to a maximum height of 3 em but does not:

```yaml
site_unit.list:
  record_type: unit
  view_type: list  # (can be list, sheet or file_list or harris_matrix)
...
  ui_elements:
...
    purpose:
      layout:
        min_width: 60%
        max_height: 3

```
