### ISSUE TITLE
Q&V: Drop parts that use a record type that doe not exist in the current project

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2729]
- coming out of #2728 

If there is a part definition that is based on a record type that is unknown in the project's dsd, the part should be skippable with the option `drop_on_unknown_record_type: True`:

```
compilations:
  cm_compilation:
    groups:
      group_2:
        type: "accordion"
        parts:
          cm_ceramics_preprocessing.list:
            text: 'ceramic preprocessing'
            position: 2

cm_ceramics_preprocessing.list:
  record_type: su_ceramics_preprocessing_entry
  drop_on_unknown_record_type: True
  view_type: list
  max_height: 20em
  fields_selection: dsd
  layout_settings:
    type: list
    orchestration_strategy: table
    order_records_by: ["category_1", "category_2", "modified"]
    allow_ordering_by: [category_1, category_2, count, weight, modified, modified_by]
    order: [category_1, category_2, count, weight, modified, modified_by]
```
