### ISSUE TITLE
Q&V: CQL Query leads to strange column information

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2765]
The following KioskQuery definition:
```
  image_load:
    name: 'Image load distribution'
    description: 'Analyze how the overall image load distributes among units, record types and years'
    type: 'CQL'
    output_type: 'list'
    query:
      meta:
        version: 0.1
      base:
        scope:
          unit: browse()
        target:
          field_or_instruction: uid_file()
        additional_fields:
          modified:
            field_or_instruction: modified
            default: null
            format: datetime(year)
      query:
        type: raw
        distinct: true
        columns:
          "record type":
            source_field: record_type
          "unit id":
            source_field: identifier
          "year":
            source_field: modified
          "file":
            source_field: data

```

leads to strange columns:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/642215b0-c0bc-44c7-adf2-3292195a9f30)

- First of all the "file" column leads to called "sketch", which stems from the locus_relations. Why of all tables is that taken from locus relations?
-  The document information shows that indeed the locus_relations table is the only included table besides unit. Why that one and not collected_material and others, too (or none of them)?
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/f0fee88c-4b40-4363-b547-b5aabfc9d2d5)
- the column order is reverse of what it was supposed to be in the query definition. But I think it would also need a way to manipulate the column order. YAML does not preserve order in dicts. 
- the unit id does not show a label presumably because #(unit/term_for_unit) cannot possibly exist outside of a view. So here the DSD label does not work for the query records. That's a general question for dynamic content in label instructions: Should one refer to records? Or only to constants? How to define a fallback (I had that a lot with query and view).
- why does it use he label for unit.arch_context at all and not rather the label "unit id"? Same for the "file" which gets its label from locus_relations.uid_sketch. But why does not happen with "modified"? 

There is a lot to debug here.
