### ISSUE TITLE
Q&V: Graph in endless loop

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2766]
the query and graph

``` YAML
header:
  version: 1
meta:
  query_type: StructuredKioskQuery
variables:
  unit_id: ["dsd('unit', 'arch_context')"]
queries:
  image_load:
    name: 'Image load distribution'
    description: 'Analyze how the overall image load distributes among units, record types and years'
    type: 'CQL'
    output_type: 'list'
    query:
      meta:
        version: 0.1
      base:
        scope:
          unit: browse()
        target:
          field_or_instruction: uid_file()
        additional_fields:
          modified:
            field_or_instruction: modified
            default: null
            format: datetime(year)
      query:
        type: raw
        distinct: true
        columns:
          "record type":
            source_field: record_type
          "unit id":
            source_field: identifier
          "year":
            source_field: modified
          "file":
            source_field: data
    charts:
      chart1:
        type: "pie"
        title: "#: % material in #(/$/constants/labels/unit) #(/variables/inputs/unit_id) by quantity"
        categories: "identifier"
        values: "file"
```

leads to an endless loop. It refreshes over and over again once the graph is activated.
