### ISSUE TITLE
Q&V: Chart - count records

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2767]
currently the preparation code for the charts try to add numerical values.
while that is okay as the default behaviour, I suggest a new "operation" attribute in the chart definition that allows counting records:

```yaml
    charts:
      chart1:
        type: "pie"
        title: "number of images per trench"
        categories: "identifier"
        values: "file"
        operation: "count"

```
