### ISSUE TITLE
Q&V: Hide data table

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2768]
Sometimes we just want to show graphs. The underlying data might really not be useful for the user (e.g. because it is full of UIDs or such). In such cases we want to hide the data table. I suggest a new output type "chart" that could also show a different icon in the query selector. 
BUT note that documentation under https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:querying :

> While a number of queries can be listed under “queries”, only list ONE query of output type list. That is the one that will be used by the KioskQueryStore.
The query of output type “list” has to have a name and should have a description if it is supposed to be saved in the KioskQueryStore

So queries with "chart" would have to be stored there, too, 

I am not entirely sure this is the best way to define this but we do need a way to hide the data table.

**Comment by urapadmin** [comment]
let's try a simple "show_rows" that hides data table and data export

**Comment by urapadmin** [comment]
### Kiosk 16.2.2
- "show_rows" it is:
```
header:
  version: 1
meta:
  query_type: StructuredKioskQuery
variables:
  unit_id: ["dsd('unit', 'arch_context')"]
queries:
  image_load:
    name: 'Image load distribution'
    description: 'Analyze how the overall image load distributes across units, record types and years'
    type: 'CQL'
    output_type: 'list'
    show_rows: false

```
- can be tested with the new "image load distribution" query
