### ISSUE TITLE
Q&V Chart: limit number of categories

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2770]
The number of images per unit shows that a bar and a pie chart have too many categories to make any sense.
So we need a new option to limit the number of categories:

```
      chart1:
        type: "bar"
        title: "#: image load by #(/$/constants/labels/unit)"
        categories: "unit id"
        values: "file"
        sort_by: "value"
        operation: "count"
        max_categories: 25

```
if max categories is given, the 24 categories with the highest value are shown while all others are summed up under "others".
