### ISSUE TITLE
Q&V: Chart: sort by value

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2771]
currently the values for the chart appear alphabetically sorted by category. Not always the best choice.
So we need a new "sort_by" field that allows to sort either by category (which is the default) or value. 
And since I am on it: Let's also have a "sort_order" that's either "asc" (default) or "desc":

``` yaml
      chart1:
        type: "bar"
        title: "#: image load by #(/$/constants/labels/unit)"
        categories: "unit id"
        values: "file"
        sort_by: "value"
        sort_order: "desc"
        operation: "count"

```
