### ISSUE TITLE
add tz fields to dsd automatically

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2786]
<html><body>
<li class="level1"><div class="li">we need to store the time zone 
information separately. Kiosk automatically creates a tz field for every
 TIMESTAMPTZ field. So the field “created” automatically gets a 
“created_tz” field. It is not explicitly mentioned in the DSD but Kiosk 
adds it automatically to the DSD. </div>
</li>
<li class="level1"><div class="li"> This field is not listed in the DSD 
file, it is automatically managed by Kiosk for every TIMESTAMP field 
that exists: </body>
</html>

``` YAML

created: [datatype(TIMESTAMP), replfield_created()]
modified: [datatype(TIMESTAMP), replfield_modified()]
```
looks in future like this (when kiosk code deals with the dsd):
``` YAML
created: [datatype(TIMESTAMP), replfield_created()]
created_tz: [datatype(TZ)]
modified: [datatype(TIMESTAMP), replfield_modified()]
modified_tz: [datatype(TZ)]
```
