### ISSUE TITLE
kiosk Query UI: result list has wrong headers

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#3139]
MY query "changed_by_x_in_timespan" has the unit and the identifier of whatever record type has been modified by a team member as a result. Apparently the query engine or whoever ignores the names of my output columns:
``` yaml
    query:
      base:
        scope:
          unit: browse()
        target:
          field_or_instruction: replfield_modified_by()
        additional_fields:
          modified:
            field_or_instruction: modified_ww()
            format: datetime(date)
            default: null
      query:
        type: raw
        distinct: true
        output_type: list
        columns:
          "asdf":
            source_field: identifier
          "archaeological identifier":
            source_field: primary_identifier
          "record type":
            source_field: record_type
          "modified":
            source_field: modified

```
Bot the "asdf" column and the "archaeological identifier" column are named "unit" for some reason.
