### ISSUE TITLE
Kiosk QueryUI: CQL queries have random column order

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#3140]
While the SQL queries simply use the order of appearance in the SQL statement, CQL queries have no defined column order.
I want to use the column order for a second thing: visibility. Columns that are not listed would be part of the result set but not visible in the grid. That's why I want to introduce a column_order statement for both CQL and SQL queries:

```
queries:
  'changed_by_x_in_timespan':
    name: 'list all archaeological entities dug by a certain team member'
    description: 'List all archaeological entites that were dug by a certain team member within a time span.'
    type: 'CQL'
    output_type: 'list'
...
    column_information:
      "archaeological identifier": ["label('archaeological identifier')", "datatype('VARCHAR')", "identifier()"]
    column_order: ["unit", "archaeological identifier", "record type", "modified"]

```
